=begin
#SendX REST API

## Introduction SendX is an email marketing product. It helps you convert website visitors to customers, send them promotional emails, engage with them using drip sequences and craft custom journeys using powerful but simple automations. The SendX API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs. The SendX Rest API doesn’t support bulk updates. You can work on only one object per request. <br> 

The version of the OpenAPI document: 1.0.0
Contact: support@sendx.io
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'date'
require 'time'

module SendX
  class Campaign
    # Encrypted ID of the campaign
    attr_accessor :id

    # Name of the campaign
    attr_accessor :name

    # Indicates if replies to the campaign should be tracked
    attr_accessor :track_reply

    # Campaign status: 0 (Draft), 1 (Scheduled), 2 (Sending), 3 (Sent), 4 (Quarantined)
    attr_accessor :status

    # Schedule type: 0 (Schedule later), 1 (Send Now), 2 (Trigger via automation), 3 (Recurring)
    attr_accessor :schedule_type

    # Condition for scheduling the campaign
    attr_accessor :schedule_condition

    # Time-related condition for the campaign
    attr_accessor :time_condition

    # Timezone for the scheduled send
    attr_accessor :timezone

    # Preferred time condition for the campaign
    attr_accessor :preferred_time_condition

    # Preferred timezone for sending the campaign
    attr_accessor :preferred_timezone

    # Strategy for the campaign
    attr_accessor :strategy

    # Indicates if the campaign should be sent in the recipient's timezone
    attr_accessor :send_in_contacts_timezone

    # Indicates if smart sending should be used
    attr_accessor :smart_send

    # Indicates if the campaign is archived
    attr_accessor :is_archived

    # Information about the sender of the campaign
    attr_accessor :sender

    # URL of the campaign's screenshot
    attr_accessor :campaign_screenshot_url

    # Segments to be included in the campaign
    attr_accessor :included_segments

    # Lists to be included in the campaign
    attr_accessor :included_lists

    # Tags to be included in the campaign
    attr_accessor :included_tags

    # Segments to be excluded from the campaign
    attr_accessor :excluded_segments

    # Lists to be excluded from the campaign
    attr_accessor :excluded_lists

    # Tags to be excluded from the campaign
    attr_accessor :excluded_tags

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'track_reply' => :'trackReply',
        :'status' => :'status',
        :'schedule_type' => :'scheduleType',
        :'schedule_condition' => :'scheduleCondition',
        :'time_condition' => :'timeCondition',
        :'timezone' => :'timezone',
        :'preferred_time_condition' => :'preferredTimeCondition',
        :'preferred_timezone' => :'preferredTimezone',
        :'strategy' => :'strategy',
        :'send_in_contacts_timezone' => :'sendInContactsTimezone',
        :'smart_send' => :'smartSend',
        :'is_archived' => :'isArchived',
        :'sender' => :'sender',
        :'campaign_screenshot_url' => :'campaignScreenshotUrl',
        :'included_segments' => :'includedSegments',
        :'included_lists' => :'includedLists',
        :'included_tags' => :'includedTags',
        :'excluded_segments' => :'excludedSegments',
        :'excluded_lists' => :'excludedLists',
        :'excluded_tags' => :'excludedTags'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'track_reply' => :'Boolean',
        :'status' => :'Integer',
        :'schedule_type' => :'Integer',
        :'schedule_condition' => :'String',
        :'time_condition' => :'String',
        :'timezone' => :'String',
        :'preferred_time_condition' => :'String',
        :'preferred_timezone' => :'String',
        :'strategy' => :'String',
        :'send_in_contacts_timezone' => :'Boolean',
        :'smart_send' => :'Boolean',
        :'is_archived' => :'Boolean',
        :'sender' => :'String',
        :'campaign_screenshot_url' => :'String',
        :'included_segments' => :'Array<String>',
        :'included_lists' => :'Array<String>',
        :'included_tags' => :'Array<String>',
        :'excluded_segments' => :'Array<String>',
        :'excluded_lists' => :'Array<String>',
        :'excluded_tags' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SendX::Campaign` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SendX::Campaign`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'track_reply')
        self.track_reply = attributes[:'track_reply']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'schedule_type')
        self.schedule_type = attributes[:'schedule_type']
      end

      if attributes.key?(:'schedule_condition')
        self.schedule_condition = attributes[:'schedule_condition']
      end

      if attributes.key?(:'time_condition')
        self.time_condition = attributes[:'time_condition']
      end

      if attributes.key?(:'timezone')
        self.timezone = attributes[:'timezone']
      end

      if attributes.key?(:'preferred_time_condition')
        self.preferred_time_condition = attributes[:'preferred_time_condition']
      end

      if attributes.key?(:'preferred_timezone')
        self.preferred_timezone = attributes[:'preferred_timezone']
      end

      if attributes.key?(:'strategy')
        self.strategy = attributes[:'strategy']
      end

      if attributes.key?(:'send_in_contacts_timezone')
        self.send_in_contacts_timezone = attributes[:'send_in_contacts_timezone']
      end

      if attributes.key?(:'smart_send')
        self.smart_send = attributes[:'smart_send']
      end

      if attributes.key?(:'is_archived')
        self.is_archived = attributes[:'is_archived']
      end

      if attributes.key?(:'sender')
        self.sender = attributes[:'sender']
      end

      if attributes.key?(:'campaign_screenshot_url')
        self.campaign_screenshot_url = attributes[:'campaign_screenshot_url']
      end

      if attributes.key?(:'included_segments')
        if (value = attributes[:'included_segments']).is_a?(Array)
          self.included_segments = value
        end
      end

      if attributes.key?(:'included_lists')
        if (value = attributes[:'included_lists']).is_a?(Array)
          self.included_lists = value
        end
      end

      if attributes.key?(:'included_tags')
        if (value = attributes[:'included_tags']).is_a?(Array)
          self.included_tags = value
        end
      end

      if attributes.key?(:'excluded_segments')
        if (value = attributes[:'excluded_segments']).is_a?(Array)
          self.excluded_segments = value
        end
      end

      if attributes.key?(:'excluded_lists')
        if (value = attributes[:'excluded_lists']).is_a?(Array)
          self.excluded_lists = value
        end
      end

      if attributes.key?(:'excluded_tags')
        if (value = attributes[:'excluded_tags']).is_a?(Array)
          self.excluded_tags = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      status_validator = EnumAttributeValidator.new('Integer', [0, 1, 2, 3, 4])
      return false unless status_validator.valid?(@status)
      schedule_type_validator = EnumAttributeValidator.new('Integer', [0, 1, 2, 3])
      return false unless schedule_type_validator.valid?(@schedule_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('Integer', [0, 1, 2, 3, 4])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] schedule_type Object to be assigned
    def schedule_type=(schedule_type)
      validator = EnumAttributeValidator.new('Integer', [0, 1, 2, 3])
      unless validator.valid?(schedule_type)
        fail ArgumentError, "invalid value for \"schedule_type\", must be one of #{validator.allowable_values}."
      end
      @schedule_type = schedule_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          track_reply == o.track_reply &&
          status == o.status &&
          schedule_type == o.schedule_type &&
          schedule_condition == o.schedule_condition &&
          time_condition == o.time_condition &&
          timezone == o.timezone &&
          preferred_time_condition == o.preferred_time_condition &&
          preferred_timezone == o.preferred_timezone &&
          strategy == o.strategy &&
          send_in_contacts_timezone == o.send_in_contacts_timezone &&
          smart_send == o.smart_send &&
          is_archived == o.is_archived &&
          sender == o.sender &&
          campaign_screenshot_url == o.campaign_screenshot_url &&
          included_segments == o.included_segments &&
          included_lists == o.included_lists &&
          included_tags == o.included_tags &&
          excluded_segments == o.excluded_segments &&
          excluded_lists == o.excluded_lists &&
          excluded_tags == o.excluded_tags
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, track_reply, status, schedule_type, schedule_condition, time_condition, timezone, preferred_time_condition, preferred_timezone, strategy, send_in_contacts_timezone, smart_send, is_archived, sender, campaign_screenshot_url, included_segments, included_lists, included_tags, excluded_segments, excluded_lists, excluded_tags].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = SendX.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
