=begin
#SendX REST API

## Introduction SendX is an email marketing product. It helps you convert website visitors to customers, send them promotional emails, engage with them using drip sequences and craft custom journeys using powerful but simple automations. The SendX API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs. The SendX Rest API doesn’t support bulk updates. You can work on only one object per request. <br> 

The version of the OpenAPI document: 1.0.1
Contact: support@sendx.io
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'date'
require 'time'

module SendX
  class ListModel
    # Encrypted ID of the list
    attr_accessor :id

    # Name of the list
    attr_accessor :name

    # Type of the list representing opt-in methods (1: Single Opt-In, 2: Double Opt-In)
    attr_accessor :type

    # Indicates if a thank-you email should be sent
    attr_accessor :send_thank_you_mail

    # Name displayed as the sender in the thank-you email
    attr_accessor :thank_you_from_name

    # Email address from which the thank-you email is sent
    attr_accessor :thank_you_from_email

    # Subject line of the thank-you email
    attr_accessor :thank_you_mail_subject

    # Plain text message body of the thank-you email
    attr_accessor :thank_you_mail_message

    # Details of the sender of the thank-you email
    attr_accessor :thank_you_sender

    # Name displayed as the sender in the confirmation email
    attr_accessor :confirm_from_name

    # Email address from which the confirmation email is sent
    attr_accessor :confirm_from_email

    # Subject line of the confirmation email
    attr_accessor :confirm_mail_subject

    # Plain text message body of the confirmation email
    attr_accessor :confirm_mail_message

    # URL of the success page after confirmation
    attr_accessor :confirm_success_page

    # Date and time when the list was created
    attr_accessor :created

    # Date and time when the list was last updated
    attr_accessor :updated

    # Details of the sender of the confirmation email
    attr_accessor :confirm_sender

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'type' => :'type',
        :'send_thank_you_mail' => :'sendThankYouMail',
        :'thank_you_from_name' => :'thankYouFromName',
        :'thank_you_from_email' => :'thankYouFromEmail',
        :'thank_you_mail_subject' => :'thankYouMailSubject',
        :'thank_you_mail_message' => :'thankYouMailMessage',
        :'thank_you_sender' => :'thankYouSender',
        :'confirm_from_name' => :'confirmFromName',
        :'confirm_from_email' => :'confirmFromEmail',
        :'confirm_mail_subject' => :'confirmMailSubject',
        :'confirm_mail_message' => :'confirmMailMessage',
        :'confirm_success_page' => :'confirmSuccessPage',
        :'created' => :'created',
        :'updated' => :'updated',
        :'confirm_sender' => :'confirmSender'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'type' => :'Integer',
        :'send_thank_you_mail' => :'Boolean',
        :'thank_you_from_name' => :'String',
        :'thank_you_from_email' => :'String',
        :'thank_you_mail_subject' => :'String',
        :'thank_you_mail_message' => :'String',
        :'thank_you_sender' => :'String',
        :'confirm_from_name' => :'String',
        :'confirm_from_email' => :'String',
        :'confirm_mail_subject' => :'String',
        :'confirm_mail_message' => :'String',
        :'confirm_success_page' => :'String',
        :'created' => :'Time',
        :'updated' => :'Time',
        :'confirm_sender' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'confirm_sender'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SendX::ListModel` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SendX::ListModel`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'send_thank_you_mail')
        self.send_thank_you_mail = attributes[:'send_thank_you_mail']
      end

      if attributes.key?(:'thank_you_from_name')
        self.thank_you_from_name = attributes[:'thank_you_from_name']
      end

      if attributes.key?(:'thank_you_from_email')
        self.thank_you_from_email = attributes[:'thank_you_from_email']
      end

      if attributes.key?(:'thank_you_mail_subject')
        self.thank_you_mail_subject = attributes[:'thank_you_mail_subject']
      end

      if attributes.key?(:'thank_you_mail_message')
        self.thank_you_mail_message = attributes[:'thank_you_mail_message']
      end

      if attributes.key?(:'thank_you_sender')
        self.thank_you_sender = attributes[:'thank_you_sender']
      end

      if attributes.key?(:'confirm_from_name')
        self.confirm_from_name = attributes[:'confirm_from_name']
      end

      if attributes.key?(:'confirm_from_email')
        self.confirm_from_email = attributes[:'confirm_from_email']
      end

      if attributes.key?(:'confirm_mail_subject')
        self.confirm_mail_subject = attributes[:'confirm_mail_subject']
      end

      if attributes.key?(:'confirm_mail_message')
        self.confirm_mail_message = attributes[:'confirm_mail_message']
      end

      if attributes.key?(:'confirm_success_page')
        self.confirm_success_page = attributes[:'confirm_success_page']
      end

      if attributes.key?(:'created')
        self.created = attributes[:'created']
      end

      if attributes.key?(:'updated')
        self.updated = attributes[:'updated']
      end

      if attributes.key?(:'confirm_sender')
        self.confirm_sender = attributes[:'confirm_sender']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      type_validator = EnumAttributeValidator.new('Integer', [0, 1])
      return false unless type_validator.valid?(@type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('Integer', [0, 1])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          type == o.type &&
          send_thank_you_mail == o.send_thank_you_mail &&
          thank_you_from_name == o.thank_you_from_name &&
          thank_you_from_email == o.thank_you_from_email &&
          thank_you_mail_subject == o.thank_you_mail_subject &&
          thank_you_mail_message == o.thank_you_mail_message &&
          thank_you_sender == o.thank_you_sender &&
          confirm_from_name == o.confirm_from_name &&
          confirm_from_email == o.confirm_from_email &&
          confirm_mail_subject == o.confirm_mail_subject &&
          confirm_mail_message == o.confirm_mail_message &&
          confirm_success_page == o.confirm_success_page &&
          created == o.created &&
          updated == o.updated &&
          confirm_sender == o.confirm_sender
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, type, send_thank_you_mail, thank_you_from_name, thank_you_from_email, thank_you_mail_subject, thank_you_mail_message, thank_you_sender, confirm_from_name, confirm_from_email, confirm_mail_subject, confirm_mail_message, confirm_success_page, created, updated, confirm_sender].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = SendX.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
