=begin
#SendX REST API

## Introduction SendX is an email marketing product. It helps you convert website visitors to customers, send them promotional emails, engage with them using drip sequences and craft custom journeys using powerful but simple automations. The SendX API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs. The SendX Rest API doesn’t support bulk updates. You can work on only one object per request. <br> 

The version of the OpenAPI document: 1.0.0
Contact: support@sendx.io
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SendX::GettingStartedApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GettingStartedApi' do
  before do
    # run before each test
    @api_instance = SendX::GettingStartedApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GettingStartedApi' do
    it 'should create an instance of GettingStartedApi' do
      expect(@api_instance).to be_instance_of(SendX::GettingStartedApi)
    end
  end

  # unit tests for identify_contact
  # Identify contact
  # Identify a contact by email address. If the contact already exists, it will be updated.
  # @param identify_request 
  # @param [Hash] opts the optional parameters
  # @return [IdentifyResponse]
  describe 'identify_contact test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tracking_contact
  # Add Tracking info
  # Track a contact
  # @param track_request 
  # @param [Hash] opts the optional parameters
  # @return [TrackResponse]
  describe 'tracking_contact test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
