=begin
#SendX REST API

## Introduction SendX is an email marketing product. It helps you convert website visitors to customers, send them promotional emails, engage with them using drip sequences and craft custom journeys using powerful but simple automations. The SendX API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs. The SendX Rest API doesn’t support bulk updates. You can work on only one object per request. <br> 

The version of the OpenAPI document: 1.0.1
Contact: support@sendx.io
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SendX::SenderApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SenderApi' do
  before do
    # run before each test
    @api_instance = SendX::SenderApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SenderApi' do
    it 'should create an instance of SenderApi' do
      expect(@api_instance).to be_instance_of(SendX::SenderApi)
    end
  end

  # unit tests for create_sender
  # Create Sender
  # Creates a new sender in the system.
  # @param sender_request 
  # @param [Hash] opts the optional parameters
  # @return [Sender]
  describe 'create_sender test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_all_senders
  # Get All Senders
  # Retrieve all senders for the team, with optional filters like offset, limit, and search.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset Number of records to skip
  # @option opts [Integer] :limit Maximum number of records to return
  # @option opts [String] :search Search keyword to filter senders by name or email
  # @return [Array<SenderResponse>]
  describe 'get_all_senders test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
