=begin
#SendX REST API

## Introduction SendX is an email marketing product. It helps you convert website visitors to customers, send them promotional emails, engage with them using drip sequences and craft custom journeys using powerful but simple automations. The SendX API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs. The SendX Rest API doesn’t support bulk updates. You can work on only one object per request. <br> 

The version of the OpenAPI document: 1.0.0
Contact: support@sendx.io
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

# Common files
require 'sendx-ruby-sdk/api_client'
require 'sendx-ruby-sdk/api_error'
require 'sendx-ruby-sdk/version'
require 'sendx-ruby-sdk/configuration'

# Models
require 'sendx-ruby-sdk/models/campaign'
require 'sendx-ruby-sdk/models/campaign_dashboard_data'
require 'sendx-ruby-sdk/models/campaign_request'
require 'sendx-ruby-sdk/models/contact'
require 'sendx-ruby-sdk/models/contact_request'
require 'sendx-ruby-sdk/models/create_response'
require 'sendx-ruby-sdk/models/custom_event_request'
require 'sendx-ruby-sdk/models/dashboard_stats'
require 'sendx-ruby-sdk/models/delete_campaign200_response'
require 'sendx-ruby-sdk/models/delete_request'
require 'sendx-ruby-sdk/models/delete_response'
require 'sendx-ruby-sdk/models/event_response'
require 'sendx-ruby-sdk/models/identify_request'
require 'sendx-ruby-sdk/models/identify_response'
require 'sendx-ruby-sdk/models/last_sent_campaign_stat'
require 'sendx-ruby-sdk/models/list_model'
require 'sendx-ruby-sdk/models/list_request'
require 'sendx-ruby-sdk/models/report_data'
require 'sendx-ruby-sdk/models/response'
require 'sendx-ruby-sdk/models/revenue_event_request'
require 'sendx-ruby-sdk/models/sender'
require 'sendx-ruby-sdk/models/sender_request'
require 'sendx-ruby-sdk/models/sender_response'
require 'sendx-ruby-sdk/models/tag'
require 'sendx-ruby-sdk/models/tag_request'
require 'sendx-ruby-sdk/models/track_request'
require 'sendx-ruby-sdk/models/track_response'

# APIs
require 'sendx-ruby-sdk/api/campaign_api'
require 'sendx-ruby-sdk/api/contact_api'
require 'sendx-ruby-sdk/api/event_api'
require 'sendx-ruby-sdk/api/getting_started_api'
require 'sendx-ruby-sdk/api/list_api'
require 'sendx-ruby-sdk/api/reports_api'
require 'sendx-ruby-sdk/api/sender_api'
require 'sendx-ruby-sdk/api/tags_api'

module SendX
  class << self
    # Customize default settings for the SDK using block.
    #   SendX.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
