=begin
#SendX REST API

## Introduction SendX is an email marketing product. It helps you convert website visitors to customers, send them promotional emails, engage with them using drip sequences and craft custom journeys using powerful but simple automations. The SendX API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs. The SendX Rest API doesn’t support bulk updates. You can work on only one object per request. <br> 

The version of the OpenAPI document: 1.0.1
Contact: support@sendx.io
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'cgi'

module SendX
  class SenderApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create Sender
    # Creates a new sender in the system.
    # @param sender_request [SenderRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Sender]
    def create_sender(sender_request, opts = {})
      data, _status_code, _headers = create_sender_with_http_info(sender_request, opts)
      data
    end

    # Create Sender
    # Creates a new sender in the system.
    # @param sender_request [SenderRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Sender, Integer, Hash)>] Sender data, response status code and response headers
    def create_sender_with_http_info(sender_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SenderApi.create_sender ...'
      end
      # verify the required parameter 'sender_request' is set
      if @api_client.config.client_side_validation && sender_request.nil?
        fail ArgumentError, "Missing the required parameter 'sender_request' when calling SenderApi.create_sender"
      end
      # resource path
      local_var_path = '/sender'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(sender_request)

      # return_type
      return_type = opts[:debug_return_type] || 'Sender'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKeyAuth']

      new_options = opts.merge(
        :operation => :"SenderApi.create_sender",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SenderApi#create_sender\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get All Senders
    # Retrieve all senders for the team, with optional filters like offset, limit, and search.
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :offset Number of records to skip (default to 0)
    # @option opts [Integer] :limit Maximum number of records to return (default to 10)
    # @option opts [String] :search Search keyword to filter senders by name or email
    # @return [Array<SenderResponse>]
    def get_all_senders(opts = {})
      data, _status_code, _headers = get_all_senders_with_http_info(opts)
      data
    end

    # Get All Senders
    # Retrieve all senders for the team, with optional filters like offset, limit, and search.
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :offset Number of records to skip (default to 0)
    # @option opts [Integer] :limit Maximum number of records to return (default to 10)
    # @option opts [String] :search Search keyword to filter senders by name or email
    # @return [Array<(Array<SenderResponse>, Integer, Hash)>] Array<SenderResponse> data, response status code and response headers
    def get_all_senders_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SenderApi.get_all_senders ...'
      end
      # resource path
      local_var_path = '/sender'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'offset'] = opts[:'offset'] if !opts[:'offset'].nil?
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'search'] = opts[:'search'] if !opts[:'search'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<SenderResponse>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKeyAuth']

      new_options = opts.merge(
        :operation => :"SenderApi.get_all_senders",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SenderApi#get_all_senders\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
